# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jon/QtSDK/test2.ui'
#
# Created: Mon May 28 21:37:27 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui



try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(685, 376)
        MainWindow.setToolTip(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.calcProj = QtGui.QPushButton(self.centralwidget)
        self.calcProj.setGeometry(QtCore.QRect(223, 2, 121, 32))
        self.calcProj.setObjectName(_fromUtf8("calcProj"))
        self.display = QtGui.QPushButton(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(340, 2, 114, 32))
        self.display.setObjectName(_fromUtf8("display"))
        self.smooth = QtGui.QLineEdit(self.centralwidget)
        self.smooth.setGeometry(QtCore.QRect(460, 6, 71, 22))
        self.smooth.setObjectName(_fromUtf8("smooth"))
        self.WkspIn = QtGui.QComboBox(self.centralwidget)
        self.WkspIn.setGeometry(QtCore.QRect(20, 4, 171, 26))
        self.WkspIn.setStatusTip(_fromUtf8(""))
        self.WkspIn.setObjectName(_fromUtf8("WkspIn"))
        self.intMin = QtGui.QLineEdit(self.centralwidget)
        self.intMin.setGeometry(QtCore.QRect(294, 100, 81, 22))
        self.intMin.setObjectName(_fromUtf8("intMin"))
        self.cutMax = QtGui.QLineEdit(self.centralwidget)
        self.cutMax.setGeometry(QtCore.QRect(380, 70, 81, 22))
        self.cutMax.setObjectName(_fromUtf8("cutMax"))
        self.delta = QtGui.QLineEdit(self.centralwidget)
        self.delta.setGeometry(QtCore.QRect(470, 70, 81, 22))
        self.delta.setObjectName(_fromUtf8("delta"))
        self.cutMin = QtGui.QLineEdit(self.centralwidget)
        self.cutMin.setGeometry(QtCore.QRect(294, 70, 81, 22))
        self.cutMin.setObjectName(_fromUtf8("cutMin"))
        self.plotOver = QtGui.QPushButton(self.centralwidget)
        self.plotOver.setGeometry(QtCore.QRect(465, 130, 91, 32))
        self.plotOver.setObjectName(_fromUtf8("plotOver"))
        self.intMax = QtGui.QLineEdit(self.centralwidget)
        self.intMax.setGeometry(QtCore.QRect(380, 100, 81, 22))
        self.intMax.setObjectName(_fromUtf8("intMax"))
        self.plot = QtGui.QPushButton(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(465, 100, 91, 32))
        self.plot.setObjectName(_fromUtf8("plot"))
        self.axis = QtGui.QComboBox(self.centralwidget)
        self.axis.setGeometry(QtCore.QRect(214, 67, 71, 26))
        self.axis.setObjectName(_fromUtf8("axis"))
        self.genScript = QtGui.QPushButton(self.centralwidget)
        self.genScript.setGeometry(QtCore.QRect(579, 270, 91, 40))
        self.genScript.setObjectName(_fromUtf8("genScript"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(321, 50, 31, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(401, 50, 31, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(495, 50, 30, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 100, 71, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(472, 30, 62, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.wkspList = QtGui.QListWidget(self.centralwidget)
        self.wkspList.setGeometry(QtCore.QRect(20, 70, 181, 231))
        self.wkspList.setObjectName(_fromUtf8("wkspList"))
        self.refresh = QtGui.QPushButton(self.centralwidget)
        self.refresh.setGeometry(QtCore.QRect(17, 30, 114, 32))
        self.refresh.setObjectName(_fromUtf8("refresh"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(320, 121, 31, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(410, 120, 31, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.FigureList = QtGui.QListWidget(self.centralwidget)
        self.FigureList.setGeometry(QtCore.QRect(210, 160, 361, 141))
        self.FigureList.setObjectName(_fromUtf8("FigureList"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(590, 184, 62, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.Temperature = QtGui.QLineEdit(self.centralwidget)
        self.Temperature.setGeometry(QtCore.QRect(584, 160, 71, 22))
        self.Temperature.setObjectName(_fromUtf8("Temperature"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(585, 230, 81, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.DBWFac = QtGui.QLineEdit(self.centralwidget)
        self.DBWFac.setGeometry(QtCore.QRect(586, 210, 71, 22))
        self.DBWFac.setObjectName(_fromUtf8("DBWFac"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(580, 250, 91, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.removeWksp = QtGui.QPushButton(self.centralwidget)
        self.removeWksp.setGeometry(QtCore.QRect(13, 310, 150, 32))
        self.removeWksp.setObjectName(_fromUtf8("removeWksp"))
        self.scalemin = QtGui.QLineEdit(self.centralwidget)
        self.scalemin.setGeometry(QtCore.QRect(294, 136, 81, 22))
        self.scalemin.setObjectName(_fromUtf8("scalemin"))
        self.scalemax = QtGui.QLineEdit(self.centralwidget)
        self.scalemax.setGeometry(QtCore.QRect(380, 135, 81, 22))
        self.scalemax.setObjectName(_fromUtf8("scalemax"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(269, 137, 21, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.removePlot = QtGui.QPushButton(self.centralwidget)
        self.removePlot.setGeometry(QtCore.QRect(210, 310, 150, 32))
        self.removePlot.setObjectName(_fromUtf8("removePlot"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 685, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuCalculations = QtGui.QMenu(self.menuBar)
        self.menuCalculations.setObjectName(_fromUtf8("menuCalculations"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionDensityOfstates = QtGui.QAction(MainWindow)
        self.actionDensityOfstates.setObjectName(_fromUtf8("actionDensityOfstates"))
        self.actionBoseFactor = QtGui.QAction(MainWindow)
        self.actionBoseFactor.setObjectName(_fromUtf8("actionBoseFactor"))
        self.menuCalculations.addAction(self.actionDensityOfstates)
        self.menuCalculations.addAction(self.actionBoseFactor)
        self.menuBar.addAction(self.menuCalculations.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.WkspIn, self.calcProj)
        MainWindow.setTabOrder(self.calcProj, self.display)
        MainWindow.setTabOrder(self.display, self.axis)
        MainWindow.setTabOrder(self.axis, self.cutMin)
        MainWindow.setTabOrder(self.cutMin, self.cutMax)
        MainWindow.setTabOrder(self.cutMax, self.delta)
        MainWindow.setTabOrder(self.delta, self.intMin)
        MainWindow.setTabOrder(self.intMin, self.intMax)
        MainWindow.setTabOrder(self.intMax, self.scalemin)
        MainWindow.setTabOrder(self.scalemin, self.scalemax)
        MainWindow.setTabOrder(self.scalemax, self.plot)
        MainWindow.setTabOrder(self.plot, self.plotOver)
        MainWindow.setTabOrder(self.plotOver, self.smooth)
        MainWindow.setTabOrder(self.smooth, self.genScript)
        MainWindow.setTabOrder(self.genScript, self.wkspList)
        MainWindow.setTabOrder(self.wkspList, self.refresh)
        MainWindow.setTabOrder(self.refresh, self.FigureList)
        MainWindow.setTabOrder(self.FigureList, self.Temperature)
        MainWindow.setTabOrder(self.Temperature, self.DBWFac)
        MainWindow.setTabOrder(self.DBWFac, self.removeWksp)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.calcProj.setText(QtGui.QApplication.translate("MainWindow", "calcProjections", None, QtGui.QApplication.UnicodeUTF8))
        self.display.setText(QtGui.QApplication.translate("MainWindow", "display", None, QtGui.QApplication.UnicodeUTF8))
        self.WkspIn.setToolTip(QtGui.QApplication.translate("MainWindow", "Avalailable Workspaces", None, QtGui.QApplication.UnicodeUTF8))
        self.intMin.setToolTip(QtGui.QApplication.translate("MainWindow", "Minimum valaue for cut integration", None, QtGui.QApplication.UnicodeUTF8))
        self.cutMax.setToolTip(QtGui.QApplication.translate("MainWindow", "Maximum valaue for cut axis", None, QtGui.QApplication.UnicodeUTF8))
        self.delta.setToolTip(QtGui.QApplication.translate("MainWindow", "Step valaue for cut axis rebin", None, QtGui.QApplication.UnicodeUTF8))
        self.cutMin.setToolTip(QtGui.QApplication.translate("MainWindow", "Minimum valaue for cut axis", None, QtGui.QApplication.UnicodeUTF8))
        self.plotOver.setToolTip(QtGui.QApplication.translate("MainWindow", "Plot cut over existing plot (Must seleect a plot below)", None, QtGui.QApplication.UnicodeUTF8))
        self.plotOver.setText(QtGui.QApplication.translate("MainWindow", "Plot Over", None, QtGui.QApplication.UnicodeUTF8))
        self.intMax.setToolTip(QtGui.QApplication.translate("MainWindow", "Maximum valaue for cut integration", None, QtGui.QApplication.UnicodeUTF8))
        self.plot.setToolTip(QtGui.QApplication.translate("MainWindow", "Plot cut", None, QtGui.QApplication.UnicodeUTF8))
        self.plot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.axis.setToolTip(QtGui.QApplication.translate("MainWindow", "Axis to cut along", None, QtGui.QApplication.UnicodeUTF8))
        self.genScript.setText(QtGui.QApplication.translate("MainWindow", "GenScript", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Integration ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Smooth", None, QtGui.QApplication.UnicodeUTF8))
        self.wkspList.setToolTip(QtGui.QApplication.translate("MainWindow", "List of transformed workspaces", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh.setToolTip(QtGui.QApplication.translate("MainWindow", "Refresh available workspaces", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.FigureList.setToolTip(QtGui.QApplication.translate("MainWindow", "List of Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Temp[K]", None, QtGui.QApplication.UnicodeUTF8))
        self.Temperature.setToolTip(QtGui.QApplication.translate("MainWindow", "Temperature of Run Units K", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "MeanSquare", None, QtGui.QApplication.UnicodeUTF8))
        self.DBWFac.setToolTip(QtGui.QApplication.translate("MainWindow", "Mean square displacement [Angstrom]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Displacement", None, QtGui.QApplication.UnicodeUTF8))
        self.removeWksp.setText(QtGui.QApplication.translate("MainWindow", "Remove workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.scalemin.setToolTip(QtGui.QApplication.translate("MainWindow", "Minimum valaue for cut integration", None, QtGui.QApplication.UnicodeUTF8))
        self.scalemax.setToolTip(QtGui.QApplication.translate("MainWindow", "Maximum valaue for cut integration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "cut", None, QtGui.QApplication.UnicodeUTF8))
        self.removePlot.setText(QtGui.QApplication.translate("MainWindow", "Remove figure", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCalculations.setTitle(QtGui.QApplication.translate("MainWindow", "Calculations", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDensityOfstates.setText(QtGui.QApplication.translate("MainWindow", "DensityOfstates", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBoseFactor.setText(QtGui.QApplication.translate("MainWindow", "BoseFactor", None, QtGui.QApplication.UnicodeUTF8))

