# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jon/QtSDK/test.ui'
#
# Created: Fri May 25 16:38:41 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(665, 334)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.calcProj = QtGui.QPushButton(self.centralwidget)
        self.calcProj.setGeometry(QtCore.QRect(223, 2, 121, 32))
        self.calcProj.setObjectName(_fromUtf8("calcProj"))
        self.display = QtGui.QPushButton(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(340, 2, 114, 32))
        self.display.setObjectName(_fromUtf8("display"))
        self.smooth = QtGui.QLineEdit(self.centralwidget)
        self.smooth.setGeometry(QtCore.QRect(460, 6, 71, 22))
        self.smooth.setObjectName(_fromUtf8("smooth"))
        self.WkspIn = QtGui.QComboBox(self.centralwidget)
        self.WkspIn.setGeometry(QtCore.QRect(20, 4, 171, 26))
        self.WkspIn.setObjectName(_fromUtf8("WkspIn"))
        self.intMin = QtGui.QLineEdit(self.centralwidget)
        self.intMin.setGeometry(QtCore.QRect(294, 100, 81, 22))
        self.intMin.setObjectName(_fromUtf8("intMin"))
        self.cutMax = QtGui.QLineEdit(self.centralwidget)
        self.cutMax.setGeometry(QtCore.QRect(380, 70, 81, 22))
        self.cutMax.setObjectName(_fromUtf8("cutMax"))
        self.delta = QtGui.QLineEdit(self.centralwidget)
        self.delta.setGeometry(QtCore.QRect(470, 70, 81, 22))
        self.delta.setObjectName(_fromUtf8("delta"))
        self.cutMin = QtGui.QLineEdit(self.centralwidget)
        self.cutMin.setGeometry(QtCore.QRect(294, 70, 81, 22))
        self.cutMin.setObjectName(_fromUtf8("cutMin"))
        self.plotOver = QtGui.QPushButton(self.centralwidget)
        self.plotOver.setGeometry(QtCore.QRect(465, 130, 91, 32))
        self.plotOver.setObjectName(_fromUtf8("plotOver"))
        self.intMax = QtGui.QLineEdit(self.centralwidget)
        self.intMax.setGeometry(QtCore.QRect(380, 100, 81, 22))
        self.intMax.setObjectName(_fromUtf8("intMax"))
        self.plot = QtGui.QPushButton(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(465, 100, 91, 32))
        self.plot.setObjectName(_fromUtf8("plot"))
        self.axis = QtGui.QComboBox(self.centralwidget)
        self.axis.setGeometry(QtCore.QRect(214, 67, 71, 26))
        self.axis.setObjectName(_fromUtf8("axis"))
        self.genScript = QtGui.QPushButton(self.centralwidget)
        self.genScript.setGeometry(QtCore.QRect(570, 260, 91, 32))
        self.genScript.setObjectName(_fromUtf8("genScript"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(314, 50, 31, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(394, 50, 31, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(484, 50, 62, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 120, 71, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(386, 120, 71, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(472, 30, 62, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.wkspList = QtGui.QListWidget(self.centralwidget)
        self.wkspList.setGeometry(QtCore.QRect(20, 70, 181, 211))
        self.wkspList.setObjectName(_fromUtf8("wkspList"))
        self.refresh = QtGui.QPushButton(self.centralwidget)
        self.refresh.setGeometry(QtCore.QRect(17, 30, 114, 32))
        self.refresh.setObjectName(_fromUtf8("refresh"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(320, 140, 31, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(410, 140, 31, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.FigureList = QtGui.QListWidget(self.centralwidget)
        self.FigureList.setGeometry(QtCore.QRect(220, 170, 341, 111))
        self.FigureList.setObjectName(_fromUtf8("FigureList"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 665, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.WkspIn, self.calcProj)
        MainWindow.setTabOrder(self.calcProj, self.display)
        MainWindow.setTabOrder(self.display, self.axis)
        MainWindow.setTabOrder(self.axis, self.cutMin)
        MainWindow.setTabOrder(self.cutMin, self.cutMax)
        MainWindow.setTabOrder(self.cutMax, self.delta)
        MainWindow.setTabOrder(self.delta, self.intMin)
        MainWindow.setTabOrder(self.intMin, self.intMax)
        MainWindow.setTabOrder(self.intMax, self.plot)
        MainWindow.setTabOrder(self.plot, self.plotOver)
        MainWindow.setTabOrder(self.plotOver, self.smooth)
        MainWindow.setTabOrder(self.smooth, self.genScript)
        MainWindow.setTabOrder(self.genScript, self.wkspList)
        MainWindow.setTabOrder(self.wkspList, self.refresh)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.calcProj.setText(QtGui.QApplication.translate("MainWindow", "calcProjections", None, QtGui.QApplication.UnicodeUTF8))
        self.display.setText(QtGui.QApplication.translate("MainWindow", "display", None, QtGui.QApplication.UnicodeUTF8))
        self.plotOver.setText(QtGui.QApplication.translate("MainWindow", "Plot Over", None, QtGui.QApplication.UnicodeUTF8))
        self.plot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.genScript.setText(QtGui.QApplication.translate("MainWindow", "GenScript", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Integration ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Integration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Smooth", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Max", None, QtGui.QApplication.UnicodeUTF8))

