######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################

wsName="Live:DGSReduction"

prescript = open('/SNS/HYSA/shared/adara/DGSPreProcessing.py').read()
postscript = open('/SNS/HYSA/shared/adara/DGSPostProcessing.py').read()

StartLiveData(UpdateEvery='10',Instrument='HYSPECA',ProcessingScript=prescript,PreserveEvents='1',PostProcessingScript=postscript,EndRunBehavior='Stop',AccumulationWorkspace='__dgs-interim',OutputWorkspace=wsName)

sqw_mat = importMatrixWorkspace(wsName)
sqw_g = sqw_mat.plotGraph2D()
#sqw_g.activeLayer().setScale(Layer.Right,0.0001,1)
sqw_g.activeLayer().logColor()

