######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################

wsName = 'Live:InstrView'
StartLiveData(UpdateEvery='5',Instrument='HYSPECA',ProcessingAlgorithm='Rebin',ProcessingProperties='Params=0,100000,100000',EndRunBehavior='Stop',OutputWorkspace=wsName)

inst_view = getInstrumentView(wsName)
inst_view.show()

