# Script automatically generated by Mantid on Wed Feb 15 15:59:58 2012
import sys
import os
if (os.environ.has_key("MANTIDPATH")):
    del os.environ["MANTIDPATH"]
sys.path.insert(0,'/opt/mantidunstable/bin')
from MantidFramework import mtd
mtd.initialize()
from mantidsimple import *

eventFileAbs=sys.argv[1]
outputDir=sys.argv[2]

eventFile = os.path.split(eventFileAbs)[-1]
nexusDir = eventFileAbs.replace(eventFile, '')
runNumber = eventFile.split('_')[2]
configService = mtd.getSettings()
dataSearchPath = configService.getDataSearchDirs()
dataSearchPath.append(nexusDir)
configService.setDataSearchDirs(dataSearchPath)

RefLReduction(RunNumbers=[int(runNumber)],
              NormalizationRunNumber=68087,
              SignalPeakPixelRange=[121, 130],
              SubtractSignalBackground=False,
              SignalBackgroundPixelRange=[111, 120],
              NormFlag=True,
              NormPeakPixelRange=[121, 131],
              NormBackgroundPixelRange=[109, 120],
              SubtractNormBackground=False,
              LowResDataAxisPixelRangeFlag=True,
              LowResDataAxisPixelRange=[140, 179],
              LowResNormAxisPixelRangeFlag=True,
              LowResNormAxisPixelRange=[139, 177],
              TOFRange=[9600.0, 21600.0],
              QMin=0.001,
              QStep=0.001,
              OutputWorkspace='reflectivity_'+runNumber)

file_name = 'reflectivity_'+runNumber+'.txt'
file_path = os.path.join(outputDir,file_name)
SaveAscii(Filename=file_path,
          InputWorkspace='reflectivity_'+runNumber,
          Separator='Tab',
          CommentIndicator='# ')

# Place holder for python script
file_path = os.path.join(outputDir, 'REF_L_'+runNumber+'.py')
f=open(file_path,'w')
f.write('# Empty file')
f.close()

# Reduction options for loading into Mantid
file_path = os.path.join(outputDir, 'REF_L_'+runNumber+'.xml')
f=open(file_path,'w')
f.write("""<Reduction>
  <instrument_name>Reflectometry</instrument_name>
  <timestamp>Wed Feb 15 15:59:58 2012</timestamp>
  <python_version>2.6.6 (r266:84292, Sep 15 2010, 16:41:53) 
[GCC 4.4.5]</python_version>
  <mantid_version>2.0.466</mantid_version>
<RefLData>
<peak_selection_type>narrow</peak_selection_type>
<from_peak_pixels>121</from_peak_pixels>
<to_peak_pixels>130</to_peak_pixels>
<peak_discrete_selection>N/A</peak_discrete_selection>
<background_flag>True</background_flag>
<back_roi1_from>111</back_roi1_from>
<back_roi1_to>120</back_roi1_to>
<back_roi2_from>0</back_roi2_from>
<back_roi2_to>0</back_roi2_to>
<from_tof_range>9600.0</from_tof_range>
<to_tof_range>21600.0</to_tof_range>
<data_sets>runNumber</data_sets>
<x_min_pixel>140</x_min_pixel>
<x_max_pixel>179</x_max_pixel>
<x_range_flag>True</x_range_flag>
<norm_flag>True</norm_flag>
<norm_x_range_flag>True</norm_x_range_flag>
<norm_x_max>177</norm_x_max>
<norm_x_min>139</norm_x_min>
<norm_from_peak_pixels>121</norm_from_peak_pixels>
<norm_to_peak_pixels>131</norm_to_peak_pixels>
<norm_background_flag>True</norm_background_flag>
<norm_from_back_pixels>109</norm_from_back_pixels>
<norm_to_back_pixels>120</norm_to_back_pixels>
<norm_dataset>68087</norm_dataset>
<q_min>0.001</q_min>
<q_step>0.001</q_step>
<auto_q_binning>False</auto_q_binning><angle_offset>0.0</angle_offset>
<angle_offset_error>0.0</angle_offset_error>
</RefLData>
</Reduction>
""")
f.close()
